use std::borrow::Cow;

use brz_http_router::{Captures, IndexedRouteRule, PathMode};
use http::Method;

use crate::{ApiMetrics, params::decode_component, route::RouteMatch};

/// Internal registration contract generated by function API macros. One descriptor groups
/// all methods of one path; its position is the API-local dispatch identifier.
#[derive(Clone, Copy)]
pub struct RouteDescriptor {
    pub path: &'static str,
    pub methods: u16,
    pub api_log_methods: u16,
    pub priority: usize,
    pub metrics: fn() -> ApiMetrics,
    /// Macro-generated segment program retained for source compatibility.
    pub program: Option<RouteProgram>,
}

/// A route template compiled by the API macro.
#[doc(hidden)]
#[derive(Clone, Copy)]
pub struct RouteProgram {
    pub segments: usize,
    pub literals: &'static [(usize, &'static str)],
    pub parameters: &'static [usize],
    pub catch_all: Option<usize>,
}

pub(super) struct RegisteredRoute {
    pub handler: usize,
    pub endpoint: usize,
    pub descriptor: RouteDescriptor,
}

#[derive(Clone, Copy)]
pub(super) struct Target {
    pub handler: usize,
    pub endpoint: Option<usize>,
    pub priority: usize,
}

/// A request's routing decision. Keep this alive through body reading/calling
/// so decoded capture values remain available to borrowed handler parameters.
pub struct PreparedRoute<'p> {
    pub(super) target: Option<Target>,
    pub(super) metric: Option<(usize, ApiMetrics)>,
    metric_owner: usize,
    pub(super) allowed: u16,
    api_log: bool,
    captures: CaptureValues<'p>,
}

impl<'p> PreparedRoute<'p> {
    pub(crate) fn legacy(_path: &'p str, metric: Option<(usize, ApiMetrics)>) -> Self {
        Self {
            target: None,
            metric,
            metric_owner: usize::MAX,
            allowed: 0,
            api_log: true,
            captures: CaptureValues::default(),
        }
    }

    #[must_use]
    pub fn metrics(&self) -> Option<ApiMetrics> {
        self.metric.map(|(_, metric)| metric)
    }

    #[must_use]
    pub fn api_log(&self) -> bool {
        self.api_log
    }

    pub(super) fn captures(&self) -> RouteMatch<'_> {
        let captures = std::array::from_fn(|index| self.captures.values[index].as_deref());
        RouteMatch::from_captures(captures, self.captures.len)
    }

    pub(super) fn consider_legacy(
        &mut self,
        handler: usize,
        priority: Option<usize>,
        metric: Option<(usize, ApiMetrics)>,
        allowed: u16,
    ) {
        self.allowed |= allowed;
        if let Some(priority) = priority {
            if self.target.is_none_or(|target| {
                priority > target.priority
                    || (priority == target.priority && handler < target.handler)
            }) {
                self.target = Some(Target {
                    handler,
                    endpoint: None,
                    priority,
                });
                self.metric = metric;
                self.metric_owner = handler;
            }
        } else if self.target.is_none() {
            if let Some((priority, _)) = metric {
                if self.metric.is_none_or(|(current, _)| {
                    priority > current || (priority == current && handler < self.metric_owner)
                }) {
                    self.metric = metric;
                    self.metric_owner = handler;
                }
            }
        }
    }
}

struct CaptureValues<'p> {
    values: [Option<Cow<'p, str>>; 8],
    len: usize,
}

impl Default for CaptureValues<'_> {
    fn default() -> Self {
        Self {
            values: std::array::from_fn(|_| None),
            len: 0,
        }
    }
}

impl<'p> CaptureValues<'p> {
    fn from_ranges(path: &'p str, ranges: &Captures, encoded: bool) -> Self {
        let mut result = Self::default();
        for (index, slot) in result.values.iter_mut().enumerate() {
            let Some((start, end)) = ranges.get(index) else {
                break;
            };
            let value = &path[start..end];
            *slot = Some(if encoded {
                decode_component(value)
            } else {
                Cow::Borrowed(value)
            });
            result.len += 1;
        }
        result
    }
}

struct Entry {
    handler: usize,
    endpoint: usize,
    methods: u16,
    api_log_methods: u16,
    priority: usize,
    metrics: fn() -> ApiMetrics,
    path: &'static str,
}

impl Entry {
    fn new(route: &RegisteredRoute) -> Self {
        Self {
            handler: route.handler,
            endpoint: route.endpoint,
            methods: route.descriptor.methods,
            api_log_methods: route.descriptor.api_log_methods,
            priority: route.descriptor.priority,
            metrics: route.descriptor.metrics,
            path: route.descriptor.path,
        }
    }
}

pub(super) struct RouteIndex {
    entries: Vec<Entry>,
    shared: brz_http_router::RouteIndex,
}

impl RouteIndex {
    pub(super) fn new(routes: &[RegisteredRoute]) -> Self {
        let entries = routes.iter().map(Entry::new).collect::<Vec<_>>();
        let shared = brz_http_router::RouteIndex::compile(entries.iter().map(|entry| {
            IndexedRouteRule::new(entry.path, methods(entry.methods), entry.priority)
        }))
        .expect("registered HTTP server routes must be valid");
        Self { entries, shared }
    }

    pub(super) fn resolve<'p>(&self, raw_path: &'p str, method: &str) -> PreparedRoute<'p> {
        let mut result = PreparedRoute::legacy(raw_path, None);
        let encoded = raw_path.as_bytes().contains(&b'%');
        let resolution = self.shared.resolve_allowing_empty_catch_all(
            method,
            raw_path,
            if encoded {
                PathMode::PercentDecoded
            } else {
                PathMode::Raw
            },
        );
        result.allowed = resolution.allowed_methods().bits() & 0x7f;

        if let Some(id) = resolution.fallback_id() {
            let entry = &self.entries[id];
            result.metric = Some((entry.priority, (entry.metrics)()));
            result.metric_owner = entry.handler;
        }
        if let Some(selected) = resolution.selected() {
            let entry = &self.entries[selected.id()];
            result.target = Some(Target {
                handler: entry.handler,
                endpoint: Some(entry.endpoint),
                priority: entry.priority,
            });
            result.api_log = entry.api_log_methods & method_bit(method) != 0;
            result.metric = Some((entry.priority, (entry.metrics)()));
            result.metric_owner = entry.handler;
            result.captures = CaptureValues::from_ranges(raw_path, selected.captures(), encoded);
        }
        result
    }
}

fn methods(bits: u16) -> Vec<Method> {
    [
        (1 << 0, Method::DELETE),
        (1 << 1, Method::GET),
        (1 << 2, Method::HEAD),
        (1 << 3, Method::OPTIONS),
        (1 << 4, Method::PATCH),
        (1 << 5, Method::POST),
        (1 << 6, Method::PUT),
    ]
    .into_iter()
    .filter_map(|(bit, method)| (bits & bit != 0).then_some(method))
    .collect()
}

fn method_bit(method: &str) -> u16 {
    match method {
        "DELETE" => 1 << 0,
        "GET" => 1 << 1,
        "HEAD" => 1 << 2,
        "OPTIONS" => 1 << 3,
        "PATCH" => 1 << 4,
        "POST" => 1 << 5,
        "PUT" => 1 << 6,
        _ => 0,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::route::match_route;

    fn metrics() -> ApiMetrics {
        ApiMetrics::new("/index-test")
    }

    fn registration(handler: usize, path: &'static str, methods: u16) -> RegisteredRoute {
        let segments: Vec<_> = path.split('/').collect();
        let literals = segments
            .iter()
            .filter(|part| !part.starts_with(':') && !part.starts_with('*'))
            .count();
        let priority =
            if path.contains("/*") { 0 } else { 1 << 24 } + literals * 1024 + segments.len();
        RegisteredRoute {
            handler,
            endpoint: 0,
            descriptor: RouteDescriptor {
                path,
                methods,
                api_log_methods: methods,
                priority,
                metrics,
                program: None,
            },
        }
    }

    #[test]
    fn shared_index_agrees_with_original_matcher_and_priority_rules() {
        let routes = [
            ("/", 2),
            ("/api/users/byname", 2),
            ("/api/users/:id", 34),
            ("/api/:kind/status", 2),
            ("/:area/users/:id", 2),
            ("/api/users/:id/skills", 2),
            ("/api/users/*rest", 64),
            ("/api/*rest", 2),
            ("/*rest", 16),
            ("/api//literal", 2),
            ("/api/users/:other", 2),
            ("/api/:kind/:id", 1),
        ]
        .into_iter()
        .enumerate()
        .map(|(id, (path, methods))| registration(id, path, methods))
        .collect::<Vec<_>>();
        let index = RouteIndex::new(&routes);
        for path in [
            "/",
            "",
            "/api",
            "/api/",
            "/api/users",
            "/api/users/",
            "/api/users/123",
            "/api/users/byname",
            "/api/users/status",
            "/api/tasks/status",
            "/api/users/123/skills",
            "/api/users/123/skills/",
            "/api/users/a/b",
            "/api/users//skills",
            "/api//literal",
            "/api/%75sers/byname",
            "/api/%75sers/123",
            "/api/users/a%2Fb",
            "/api/users/%E4%B8%AD",
            "/api/users/%FF",
            "/api/users/%",
            "//api/users/123",
        ] {
            for method in [
                "GET", "POST", "PUT", "DELETE", "PATCH", "HEAD", "OPTIONS", "CUSTOM",
            ] {
                let mut expected = None;
                let mut allowed = 0;
                for route in &routes {
                    if let Some(captures) = match_route(path, route.descriptor.path) {
                        allowed |= route.descriptor.methods;
                        if route.descriptor.methods & method_bit(method) != 0
                            && expected.as_ref().is_none_or(|(priority, _, _)| {
                                route.descriptor.priority > *priority
                            })
                        {
                            expected = Some((route.descriptor.priority, route.handler, captures));
                        }
                    }
                }
                let actual = index.resolve(path, method);
                assert_eq!(
                    actual
                        .target
                        .map(|target| (target.priority, target.handler)),
                    expected
                        .as_ref()
                        .map(|(priority, handler, _)| (*priority, *handler)),
                    "{method} {path}"
                );
                assert_eq!(index.resolve(path, "").allowed, allowed, "Allow: {path}");
                if let Some((_, _, expected)) = expected {
                    for capture in 0..8 {
                        assert_eq!(
                            actual.captures().capture(capture),
                            expected.capture(capture),
                            "{method} {path} capture {capture}"
                        );
                    }
                } else {
                    assert_eq!(actual.allowed, allowed, "{method} {path}");
                }
            }
        }
    }

    #[test]
    fn deep_paths_and_eight_captures_have_no_matching_limit() {
        let paths = [
            format!("/{}/:id", ["part"; 40].join("/")),
            "/:a/:b/:c/:d/:e/:f/:g/:h".into(),
        ];
        let routes = paths
            .into_iter()
            .enumerate()
            .map(|(id, path)| registration(id, Box::leak(path.into_boxed_str()), 2))
            .collect::<Vec<_>>();
        let index = RouteIndex::new(&routes);
        let deep = routes[0].descriptor.path.replace(":id", "123");
        assert_eq!(
            index.resolve(&deep, "GET").captures().capture(0),
            Some("123")
        );
        let captured = index.resolve("/1/2/3/4/5/6/7/8", "GET");
        assert_eq!(captured.captures().capture(0), Some("1"));
        assert_eq!(captured.captures().capture(7), Some("8"));
    }
}
