use std::borrow::Cow;
use std::cmp::Reverse;
use std::collections::HashMap;

use crate::{ApiMetrics, params::decode_component, route::RouteMatch};

const STATIC_BUCKETS: usize = 128;
const INLINE_SEGMENTS: usize = 32;

/// Internal registration contract generated by function API macros. One descriptor groups
/// all methods of one path; its position is the API-local dispatch identifier.
#[derive(Clone, Copy)]
pub struct RouteDescriptor {
    pub path: &'static str,
    pub methods: u16,
    pub priority: usize,
    pub metrics: fn() -> ApiMetrics,
    /// Macro-generated segment program. Handwritten descriptors may leave this
    /// as `None` and use the startup parser for compatibility.
    pub program: Option<RouteProgram>,
}

/// A route template compiled by the API macro into constant matching data.
#[doc(hidden)]
#[derive(Clone, Copy)]
pub struct RouteProgram {
    pub segments: usize,
    pub literals: &'static [(usize, &'static str)],
    pub parameters: &'static [usize],
    pub catch_all: Option<usize>,
}

pub(super) struct RegisteredRoute {
    pub handler: usize,
    pub endpoint: usize,
    pub descriptor: RouteDescriptor,
}

#[derive(Clone, Copy)]
pub(super) struct Target {
    pub handler: usize,
    pub endpoint: Option<usize>,
    pub priority: usize,
}

/// A request's routing decision. Keep this alive through body reading/calling
/// so decoded capture values remain available to borrowed handler parameters.
pub struct PreparedRoute<'p> {
    path: &'p str,
    pub(super) target: Option<Target>,
    pub(super) metric: Option<(usize, ApiMetrics)>,
    metric_owner: usize,
    pub(super) allowed: u16,
    captures: CaptureValues<'p>,
}

impl<'p> PreparedRoute<'p> {
    pub(crate) fn legacy(path: &'p str, metric: Option<(usize, ApiMetrics)>) -> Self {
        Self {
            path,
            target: None,
            metric,
            metric_owner: usize::MAX,
            allowed: 0,
            captures: CaptureValues::default(),
        }
    }

    #[must_use]
    pub fn metrics(&self) -> Option<ApiMetrics> {
        self.metric.map(|(_, metric)| metric)
    }

    pub(super) fn captures(&self) -> RouteMatch<'_> {
        let captures = std::array::from_fn(|index| self.captures.values[index].as_deref());
        RouteMatch::from_captures(captures, self.captures.len)
    }

    fn consider(
        &mut self,
        entry: &Entry,
        ranges: CaptureRanges,
        method: u16,
        encoded: bool,
    ) -> bool {
        self.allowed |= entry.methods;
        let metric = Some((entry.priority, (entry.metrics)()));
        if self
            .metric
            .is_none_or(|(priority, _)| entry.priority > priority)
        {
            self.metric = metric;
            self.metric_owner = entry.handler;
        }
        if entry.methods & method == 0 {
            return false;
        }
        self.target = Some(Target {
            handler: entry.handler,
            endpoint: Some(entry.endpoint),
            priority: entry.priority,
        });
        self.metric = metric;
        self.metric_owner = entry.handler;
        self.captures = CaptureValues::from_ranges(self.path, &ranges, encoded);
        true
    }

    pub(super) fn consider_legacy(
        &mut self,
        handler: usize,
        priority: Option<usize>,
        metric: Option<(usize, ApiMetrics)>,
        allowed: u16,
    ) {
        self.allowed |= allowed;
        if let Some(priority) = priority {
            if self.target.is_none_or(|target| {
                priority > target.priority
                    || (priority == target.priority && handler < target.handler)
            }) {
                self.target = Some(Target {
                    handler,
                    endpoint: None,
                    priority,
                });
                self.metric = metric;
                self.metric_owner = handler;
            }
        } else if self.target.is_none() {
            if let Some((priority, _)) = metric {
                if self.metric.is_none_or(|(current, _)| {
                    priority > current || (priority == current && handler < self.metric_owner)
                }) {
                    self.metric = metric;
                    self.metric_owner = handler;
                }
            }
        }
    }
}

struct CaptureValues<'p> {
    values: [Option<Cow<'p, str>>; 8],
    len: usize,
}

impl Default for CaptureValues<'_> {
    fn default() -> Self {
        Self {
            values: std::array::from_fn(|_| None),
            len: 0,
        }
    }
}

impl<'p> CaptureValues<'p> {
    fn from_ranges(path: &'p str, ranges: &CaptureRanges, encoded: bool) -> Self {
        let mut result = Self::default();
        for (slot, &(start, end)) in result.values.iter_mut().zip(&ranges.values[..ranges.len]) {
            let value = &path[start..end];
            *slot = Some(if encoded {
                decode_component(value)
            } else {
                Cow::Borrowed(value)
            });
        }
        result.len = ranges.len;
        result
    }
}

#[derive(Clone, Copy, Default)]
struct CaptureRanges {
    values: [(usize, usize); 8],
    len: usize,
}

impl CaptureRanges {
    fn push(&mut self, range: (usize, usize)) -> Option<()> {
        *self.values.get_mut(self.len)? = range;
        self.len += 1;
        Some(())
    }
}

#[derive(Clone, Copy, Default)]
struct Bucket {
    start: usize,
    end: usize,
}

struct ParameterBucket {
    segments: usize,
    range: Bucket,
    suffix_literals: HashMap<&'static str, Vec<usize>>,
    suffix_parameters: Vec<usize>,
}

struct Entry {
    path: &'static str,
    handler: usize,
    endpoint: usize,
    methods: u16,
    priority: usize,
    metrics: fn() -> ApiMetrics,
    segments: usize,
    literals: Vec<(usize, &'static str)>,
    parameters: Vec<usize>,
    catch_all: Option<usize>,
}

impl Entry {
    fn new(route: &RegisteredRoute) -> Self {
        let descriptor = route.descriptor;
        let (segments, literals, parameters, catch_all) = descriptor.program.map_or_else(
            || {
                let mut literals = Vec::new();
                let mut parameters = Vec::new();
                let mut catch_all = None;
                let mut segments = 0;
                for (position, segment) in descriptor.path.split('/').enumerate() {
                    segments += 1;
                    if segment.starts_with('*') {
                        catch_all = Some(position);
                    } else if segment.starts_with(':') {
                        parameters.push(position);
                    } else {
                        literals.push((position, segment));
                    }
                }
                (segments, literals, parameters, catch_all)
            },
            |program| {
                (
                    program.segments,
                    program.literals.to_vec(),
                    program.parameters.to_vec(),
                    program.catch_all,
                )
            },
        );
        Self {
            path: descriptor.path,
            handler: route.handler,
            endpoint: route.endpoint,
            methods: descriptor.methods,
            priority: descriptor.priority,
            metrics: descriptor.metrics,
            segments,
            literals,
            parameters,
            catch_all,
        }
    }

    fn key(&self) -> (Reverse<usize>, usize, usize) {
        (Reverse(self.priority), self.handler, self.endpoint)
    }

    fn matches(&self, path: &str, segments: &Segments, encoded: bool) -> Option<CaptureRanges> {
        if let Some(prefix) = self.catch_all {
            if segments.len < prefix {
                return None;
            }
        } else if segments.len != self.segments {
            return None;
        }
        for &(position, literal) in &self.literals {
            let (start, end) = segments.get(position)?;
            let actual = &path[start..end];
            if if encoded {
                decode_component(actual) != literal
            } else {
                actual != literal
            } {
                return None;
            }
        }
        let mut captures = CaptureRanges::default();
        for &position in &self.parameters {
            let range = segments.get(position)?;
            if range.0 == range.1 {
                return None;
            }
            captures.push(range)?;
        }
        if let Some(position) = self.catch_all {
            let start = segments.get(position).map_or(path.len(), |range| range.0);
            captures.push((start, path.len()))?;
        }
        Some(captures)
    }
}

/// A bounded stack fast path without imposing a URL depth limit.
struct Segments {
    inline: [(usize, usize); INLINE_SEGMENTS],
    overflow: Vec<(usize, usize)>,
    len: usize,
}

impl Segments {
    fn new(path: &str) -> Self {
        let mut result = Self {
            inline: [(0, 0); INLINE_SEGMENTS],
            overflow: Vec::new(),
            len: 0,
        };
        let mut start = 0;
        // Preserve both the leading empty segment and trailing/interior empty
        // segments, exactly like the original match_route implementation.
        for segment in path.split('/') {
            let range = (start, start + segment.len());
            if result.len < INLINE_SEGMENTS {
                result.inline[result.len] = range;
            } else {
                result.overflow.push(range);
            }
            result.len += 1;
            start += segment.len() + 1;
        }
        result
    }

    fn get(&self, position: usize) -> Option<(usize, usize)> {
        if position >= self.len {
            return None;
        }
        if position < INLINE_SEGMENTS {
            Some(self.inline[position])
        } else {
            self.overflow.get(position - INLINE_SEGMENTS).copied()
        }
    }
}

pub(super) struct RouteIndex {
    static_buckets: [Bucket; STATIC_BUCKETS],
    long_buckets: Vec<(usize, Bucket)>,
    statics: Vec<Entry>,
    static_segment_buckets: Vec<(usize, Bucket)>,
    static_segments: Vec<usize>,
    parameter_buckets: Vec<ParameterBucket>,
    parameters: Vec<Entry>,
    wildcards: Vec<Entry>,
}

impl RouteIndex {
    pub(super) fn new(routes: &[RegisteredRoute]) -> Self {
        let mut statics = Vec::new();
        let mut parameters = Vec::new();
        let mut wildcards = Vec::new();
        for route in routes {
            let entry = Entry::new(route);
            if entry.catch_all.is_some() {
                wildcards.push(entry);
            } else if entry.parameters.is_empty() {
                statics.push(entry);
            } else {
                parameters.push(entry);
            }
        }
        statics.sort_by_key(|entry| (entry.path.len(), entry.key()));
        parameters.sort_by_key(|entry| (entry.segments, entry.key()));
        wildcards.sort_by_key(Entry::key);

        // Rare literals reject candidates sooner. Tie-break towards the suffix,
        // but don't assume the final segment is always the useful discriminator.
        let mut frequencies = HashMap::new();
        for entry in &parameters {
            for &(position, literal) in &entry.literals {
                *frequencies
                    .entry((entry.segments, position, literal))
                    .or_insert(0usize) += 1;
            }
        }
        for entry in &mut parameters {
            entry.literals.sort_by_key(|&(position, literal)| {
                (
                    frequencies[&(entry.segments, position, literal)],
                    Reverse(position),
                )
            });
        }

        let mut static_buckets = [Bucket::default(); STATIC_BUCKETS];
        let mut long_buckets = Vec::new();
        for (length, bucket) in buckets(&statics, |entry| entry.path.len()) {
            if let Some(slot) = static_buckets.get_mut(length) {
                *slot = bucket;
            } else {
                long_buckets.push((length, bucket));
            }
        }
        let mut static_segments = (0..statics.len()).collect::<Vec<_>>();
        static_segments.sort_by_key(|&index| (statics[index].segments, statics[index].key()));
        let static_segment_buckets =
            index_buckets(&static_segments, |index| statics[*index].segments);

        let parameter_buckets = buckets(&parameters, |entry| entry.segments)
            .into_iter()
            .map(|(segments, range)| {
                let mut suffix_literals: HashMap<&'static str, Vec<usize>> = HashMap::new();
                let mut suffix_parameters = Vec::new();
                for (index, entry) in parameters
                    .iter()
                    .enumerate()
                    .take(range.end)
                    .skip(range.start)
                {
                    if let Some((_, literal)) = entry
                        .literals
                        .iter()
                        .find(|(position, _)| *position + 1 == entry.segments)
                    {
                        suffix_literals.entry(literal).or_default().push(index);
                    } else {
                        suffix_parameters.push(index);
                    }
                }
                ParameterBucket {
                    segments,
                    range,
                    suffix_literals,
                    suffix_parameters,
                }
            })
            .collect();
        Self {
            static_buckets,
            long_buckets,
            statics,
            static_segment_buckets,
            static_segments,
            parameter_buckets,
            parameters,
            wildcards,
        }
    }

    pub(super) fn resolve<'p>(&self, raw_path: &'p str, method: &str) -> PreparedRoute<'p> {
        let mut result = PreparedRoute::legacy(raw_path, None);
        let method = method_bit(method);
        let length = raw_path.len();
        let bucket = self
            .static_buckets
            .get(length)
            .copied()
            .unwrap_or_else(|| find_bucket(&self.long_buckets, length));
        for entry in &self.statics[bucket.start..bucket.end] {
            if raw_path == entry.path
                && result.consider(entry, CaptureRanges::default(), method, false)
            {
                return result;
            }
        }
        let encoded = raw_path.as_bytes().contains(&b'%');
        let encoded_static = encoded && !self.statics.is_empty();
        if !encoded_static && self.parameters.is_empty() && self.wildcards.is_empty() {
            return result;
        }
        let segments = Segments::new(raw_path);
        if encoded_static {
            let bucket = find_bucket(&self.static_segment_buckets, segments.len);
            for &index in &self.static_segments[bucket.start..bucket.end] {
                let entry = &self.statics[index];
                if let Some(captures) = entry.matches(raw_path, &segments, encoded) {
                    if result.consider(entry, captures, method, encoded) {
                        return result;
                    }
                }
            }
        }
        if let Some(bucket) = find_parameter_bucket(&self.parameter_buckets, segments.len) {
            if bucket.suffix_literals.is_empty() {
                for entry in &self.parameters[bucket.range.start..bucket.range.end] {
                    if let Some(captures) = entry.matches(raw_path, &segments, encoded) {
                        if result.consider(entry, captures, method, encoded) {
                            return result;
                        }
                    }
                }
            } else {
                let suffix_literals = segments
                    .get(segments.len - 1)
                    .map(|(start, end)| {
                        let value = &raw_path[start..end];
                        if encoded {
                            decode_component(value)
                        } else {
                            Cow::Borrowed(value)
                        }
                    })
                    .as_deref()
                    .and_then(|last| bucket.suffix_literals.get(last))
                    .map_or(&[][..], Vec::as_slice);
                if self.resolve_parameter_candidates(
                    &mut result,
                    &segments,
                    method,
                    encoded,
                    suffix_literals,
                    &bucket.suffix_parameters,
                ) {
                    return result;
                }
            }
        }
        for entry in &self.wildcards {
            if let Some(captures) = entry.matches(raw_path, &segments, encoded) {
                if result.consider(entry, captures, method, encoded) {
                    return result;
                }
            }
        }
        result
    }

    fn resolve_parameter_candidates(
        &self,
        result: &mut PreparedRoute<'_>,
        segments: &Segments,
        method: u16,
        encoded: bool,
        suffix_literals: &[usize],
        suffix_parameters: &[usize],
    ) -> bool {
        let mut literal = 0;
        let mut parameter = 0;
        while literal < suffix_literals.len() || parameter < suffix_parameters.len() {
            let index = match (
                suffix_literals.get(literal).copied(),
                suffix_parameters.get(parameter).copied(),
            ) {
                (Some(left), Some(right)) => {
                    if self.parameters[left].key() <= self.parameters[right].key() {
                        literal += 1;
                        left
                    } else {
                        parameter += 1;
                        right
                    }
                }
                (Some(index), None) => {
                    literal += 1;
                    index
                }
                (None, Some(index)) => {
                    parameter += 1;
                    index
                }
                (None, None) => unreachable!(),
            };
            let entry = &self.parameters[index];
            if let Some(captures) = entry.matches(result.path, segments, encoded) {
                if result.consider(entry, captures, method, encoded) {
                    return true;
                }
            }
        }
        false
    }
}

fn buckets(entries: &[Entry], key: impl Fn(&Entry) -> usize) -> Vec<(usize, Bucket)> {
    let mut result: Vec<(usize, Bucket)> = Vec::new();
    for (index, entry) in entries.iter().enumerate() {
        let key = key(entry);
        if let Some((last, bucket)) = result.last_mut() {
            if *last == key {
                bucket.end = index + 1;
                continue;
            }
        }
        result.push((
            key,
            Bucket {
                start: index,
                end: index + 1,
            },
        ));
    }
    result
}

fn index_buckets(entries: &[usize], key: impl Fn(&usize) -> usize) -> Vec<(usize, Bucket)> {
    let mut result: Vec<(usize, Bucket)> = Vec::new();
    for (index, entry) in entries.iter().enumerate() {
        let key = key(entry);
        if let Some((last, bucket)) = result.last_mut() {
            if *last == key {
                bucket.end = index + 1;
                continue;
            }
        }
        result.push((
            key,
            Bucket {
                start: index,
                end: index + 1,
            },
        ));
    }
    result
}

fn find_bucket(buckets: &[(usize, Bucket)], key: usize) -> Bucket {
    buckets
        .binary_search_by_key(&key, |(key, _)| *key)
        .ok()
        .map_or_else(Bucket::default, |index| buckets[index].1)
}

fn find_parameter_bucket(buckets: &[ParameterBucket], segments: usize) -> Option<&ParameterBucket> {
    buckets
        .binary_search_by_key(&segments, |bucket| bucket.segments)
        .ok()
        .map(|index| &buckets[index])
}

fn method_bit(method: &str) -> u16 {
    match method {
        "DELETE" => 1,
        "GET" => 2,
        "HEAD" => 4,
        "OPTIONS" => 8,
        "PATCH" => 16,
        "POST" => 32,
        "PUT" => 64,
        _ => 0,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::route::match_route;

    fn metrics() -> ApiMetrics {
        ApiMetrics::new("/index-test")
    }

    fn registration(handler: usize, path: &'static str, methods: u16) -> RegisteredRoute {
        let segments: Vec<_> = path.split('/').collect();
        let literals = segments
            .iter()
            .filter(|part| !part.starts_with(':') && !part.starts_with('*'))
            .count();
        let priority =
            if path.contains("/*") { 0 } else { 1 << 24 } + literals * 1024 + segments.len();
        RegisteredRoute {
            handler,
            endpoint: 0,
            descriptor: RouteDescriptor {
                path,
                methods,
                priority,
                metrics,
                program: None,
            },
        }
    }

    #[test]
    fn buckets_agree_with_original_matcher_and_priority_rules() {
        let routes = [
            ("/", 2),
            ("/api/users/byname", 2),
            ("/api/users/:id", 34),
            ("/api/:kind/status", 2),
            ("/:area/users/:id", 2),
            ("/api/users/:id/skills", 2),
            ("/api/users/*rest", 64),
            ("/api/*rest", 2),
            ("/*rest", 16),
            ("/api//literal", 2),
            ("/api/users/:other", 2),
            ("/api/:kind/:id", 1),
        ]
        .into_iter()
        .enumerate()
        .map(|(id, (path, methods))| registration(id, path, methods))
        .collect::<Vec<_>>();
        let index = RouteIndex::new(&routes);
        for path in [
            "/",
            "",
            "/api",
            "/api/",
            "/api/users",
            "/api/users/",
            "/api/users/123",
            "/api/users/byname",
            "/api/users/status",
            "/api/tasks/status",
            "/api/users/123/skills",
            "/api/users/123/skills/",
            "/api/users/a/b",
            "/api/users//skills",
            "/api//literal",
            "/api/%75sers/byname",
            "/api/%75sers/123",
            "/api/users/a%2Fb",
            "/api/users/%E4%B8%AD",
            "/api/users/%FF",
            "/api/users/%",
            "//api/users/123",
        ] {
            for method in [
                "GET", "POST", "PUT", "DELETE", "PATCH", "HEAD", "OPTIONS", "CUSTOM",
            ] {
                let mut expected = None;
                let mut allowed = 0;
                for route in &routes {
                    if let Some(captures) = match_route(path, route.descriptor.path) {
                        allowed |= route.descriptor.methods;
                        if route.descriptor.methods & method_bit(method) != 0
                            && expected.as_ref().is_none_or(|(priority, _, _)| {
                                route.descriptor.priority > *priority
                            })
                        {
                            expected = Some((route.descriptor.priority, route.handler, captures));
                        }
                    }
                }
                let actual = index.resolve(path, method);
                assert_eq!(
                    actual
                        .target
                        .map(|target| (target.priority, target.handler)),
                    expected
                        .as_ref()
                        .map(|(priority, handler, _)| (*priority, *handler)),
                    "{method} {path}"
                );
                assert_eq!(index.resolve(path, "").allowed, allowed, "Allow: {path}");
                if let Some((_, _, expected)) = expected {
                    for capture in 0..8 {
                        assert_eq!(
                            actual.captures().capture(capture),
                            expected.capture(capture),
                            "{method} {path} capture {capture}"
                        );
                    }
                } else {
                    assert_eq!(actual.allowed, allowed, "{method} {path}");
                }
            }
        }
    }

    #[test]
    fn long_paths_deep_paths_and_length_collisions_have_no_fixed_limit() {
        let paths = [
            format!("/{}", "x".repeat(126)),
            format!("/{}", "x".repeat(127)),
            format!("/{}", "x".repeat(128)),
            format!("/{}", "x".repeat(199)),
            "/api/users/me".into(),
            "/api/tasks/me".into(),
            "/中文/路径".into(),
            format!("/{}/:id", ["part"; 40].join("/")),
            "/:a/:b/:c/:d/:e/:f/:g/:h".into(),
        ];
        let routes = paths
            .into_iter()
            .enumerate()
            .map(|(id, path)| registration(id, Box::leak(path.into_boxed_str()), 2))
            .collect::<Vec<_>>();
        let index = RouteIndex::new(&routes);
        for route in &routes {
            let path = if route.handler == 8 {
                "/1/2/3/4/5/6/7/8".into()
            } else {
                route.descriptor.path.replace(":id", "123")
            };
            let actual = index.resolve(&path, "GET");
            assert_eq!(actual.target.unwrap().handler, route.handler, "{path}");
            if route.handler == 7 {
                assert_eq!(actual.captures().capture(0), Some("123"));
            }
            if route.handler == 8 {
                assert_eq!(actual.captures().capture(7), Some("8"));
            }
        }
        assert!(index.resolve("/api/other/me", "GET").target.is_none());
    }
}
