[package]
name = "brz-http-server-macros"
version = "0.0.10"
edition = "2024"
rust-version = "1.85"
description = "Static HTTP API macros for http-server"
license = "MIT OR Apache-2.0"
repository = "https://github.com/we-breeze/http-server"

[lib]
proc-macro = true

[dependencies]
proc-macro-crate = "3"
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full", "visit-mut"] }

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
