use serde::Serialize;

use crate::{EphemeralBytesArena, Response, StatusCode};

#[doc(hidden)]
pub fn json_body<'a, T>(body: &'a [u8]) -> Result<T, serde_json::Error>
where
    T: serde::Deserialize<'a>,
{
    serde_json::from_slice(body)
}

#[doc(hidden)]
#[must_use]
pub fn is_json_content_type(value: Option<&[u8]>) -> bool {
    let Some(value) = value else {
        return false;
    };
    let Ok(value) = std::str::from_utf8(value) else {
        return false;
    };
    value
        .split_once(';')
        .map_or(value, |(media_type, _)| media_type)
        .trim_matches([' ', '\t'])
        .eq_ignore_ascii_case("application/json")
}

#[doc(hidden)]
pub fn json_response<T>(value: T, arena: &EphemeralBytesArena) -> Response
where
    T: Serialize,
{
    json_response_with_status(StatusCode::OK, value, arena)
}

#[doc(hidden)]
pub fn json_result_response<T, E>(
    result: std::result::Result<T, E>,
    arena: &EphemeralBytesArena,
) -> Response
where
    T: Serialize,
    E: IntoHttpError,
{
    match result {
        Ok(value) => json_response(value, arena),
        Err(error) => error.into_http_error(arena),
    }
}

fn json_response_with_status<T>(
    status: StatusCode,
    value: T,
    arena: &EphemeralBytesArena,
) -> Response
where
    T: Serialize,
{
    match encode_json(value, arena) {
        Ok(body) => Response::segmented(status, body).content_type("application/json"),
        Err(_) => Response::conversion_failure(),
    }
}

/// Converts a business failure into an HTTP response generated by an API macro.
pub trait IntoHttpError {
    fn into_http_error(self, arena: &EphemeralBytesArena) -> Response;
}

/// Default structured HTTP API failure.
#[derive(Debug)]
pub struct ApiError {
    status: StatusCode,
    message: String,
}

impl std::fmt::Display for ApiError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&self.message)
    }
}

impl std::error::Error for ApiError {}

impl ApiError {
    #[must_use]
    pub fn new(status: StatusCode, message: impl Into<String>) -> Self {
        Self {
            status,
            message: message.into(),
        }
    }

    #[must_use]
    pub fn bad_request(message: impl Into<String>) -> Self {
        Self::new(StatusCode::BAD_REQUEST, message)
    }

    /// Returns a `403 Forbidden` API failure.
    ///
    /// Use this after authentication has established the caller's identity but
    /// authorization denies access to the requested resource or operation.
    #[must_use]
    pub fn forbidden(message: impl Into<String>) -> Self {
        Self::new(StatusCode::FORBIDDEN, message)
    }
}

/// Default result type for business functions exported through function API macros.
pub type ApiResult<T> = std::result::Result<T, ApiError>;

impl IntoHttpError for ApiError {
    fn into_http_error(self, arena: &EphemeralBytesArena) -> Response {
        json_response_with_status(
            self.status,
            ErrorPayload {
                error: self.message,
            },
            arena,
        )
    }
}

impl From<crate::HeaderBlockError> for ApiError {
    fn from(error: crate::HeaderBlockError) -> Self {
        Self::new(StatusCode::INTERNAL_SERVER_ERROR, error.to_string())
    }
}

impl IntoHttpError for crate::HeaderBlockError {
    fn into_http_error(self, arena: &EphemeralBytesArena) -> Response {
        ApiError::from(self).into_http_error(arena)
    }
}

impl From<crate::BodyError> for ApiError {
    fn from(error: crate::BodyError) -> Self {
        let status = if matches!(error, crate::BodyError::UnsupportedMediaType) {
            StatusCode::UNSUPPORTED_MEDIA_TYPE
        } else {
            StatusCode::BAD_REQUEST
        };
        Self::new(status, error.to_string())
    }
}

impl IntoHttpError for crate::BodyError {
    fn into_http_error(self, arena: &EphemeralBytesArena) -> Response {
        ApiError::from(self).into_http_error(arena)
    }
}

#[derive(Serialize)]
struct ErrorPayload {
    error: String,
}

fn encode_json<T>(
    value: T,
    arena: &EphemeralBytesArena,
) -> Result<brz_io::Reader, serde_json::Error>
where
    T: Serialize,
{
    let mut output = brz_io::Writer::new(arena);
    serde_json::to_writer(&mut output, &value)?;
    Ok(output.into_reader())
}

#[cfg(test)]
mod tests {
    use serde::Serialize;
    use std::cell::Cell;

    struct Once(Cell<usize>);

    impl Serialize for Once {
        fn serialize<S: serde::Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error> {
            self.0.set(self.0.get() + 1);
            assert_eq!(self.0.get(), 1, "JSON must be serialized only once");
            serializer.serialize_str("a long response crossing arena segments")
        }
    }

    #[test]
    fn response_serializes_once_into_segments() {
        let value = Once(Cell::new(0));
        let arena = crate::EphemeralBytesArena::new(3);
        let output = super::encode_json(&value, &arena).unwrap();
        assert_eq!(
            output.as_slice(),
            br#""a long response crossing arena segments""#
        );
        assert_eq!(value.0.get(), 1);
    }
}
