use std::io::{self, Write};

use serde::Serialize;

use crate::{EphemeralBytesArena, EphemeralBytesMut, Response, StatusCode};

/// Storage for borrowed JSON fields, including strings requiring unescaping.
#[doc(hidden)]
pub struct JsonBody<'a> {
    raw: &'a [u8],
    decoded: Option<serde_json::Value>,
}

impl<'a> JsonBody<'a> {
    /// # Errors
    /// Returns an error when escaped JSON cannot be decoded.
    pub fn new(raw: &'a [u8]) -> Result<Self, serde_json::Error> {
        let decoded = if raw.contains(&b'\\') {
            Some(serde_json::from_slice(raw)?)
        } else {
            None
        };
        Ok(Self { raw, decoded })
    }

    /// # Errors
    /// Returns an error when the body cannot become the business type.
    pub fn decode<'b, T: serde::Deserialize<'b>>(&'b self) -> Result<T, serde_json::Error> {
        match &self.decoded {
            Some(value) => T::deserialize(value),
            None => serde_json::from_slice(self.raw),
        }
    }
}

#[doc(hidden)]
pub fn json_body<'a, T>(body: &'a [u8]) -> Result<T, serde_json::Error>
where
    T: serde::Deserialize<'a>,
{
    serde_json::from_slice(body)
}

#[doc(hidden)]
#[must_use]
pub fn is_json_content_type(value: Option<&[u8]>) -> bool {
    let Some(value) = value else {
        return false;
    };
    let Ok(value) = std::str::from_utf8(value) else {
        return false;
    };
    value
        .split_once(';')
        .map_or(value, |(media_type, _)| media_type)
        .trim_matches([' ', '\t'])
        .eq_ignore_ascii_case("application/json")
}

#[doc(hidden)]
pub fn json_response<T>(value: T, arena: &EphemeralBytesArena) -> Response
where
    T: Serialize,
{
    json_response_with_status(StatusCode::OK, value, arena)
}

#[doc(hidden)]
pub fn json_result_response<T, E>(
    result: std::result::Result<T, E>,
    arena: &EphemeralBytesArena,
) -> Response
where
    T: Serialize,
    E: IntoHttpError,
{
    match result {
        Ok(value) => json_response(value, arena),
        Err(error) => error.into_http_error(arena),
    }
}

fn json_response_with_status<T>(
    status: StatusCode,
    value: T,
    arena: &EphemeralBytesArena,
) -> Response
where
    T: Serialize,
{
    match encode_json(value, arena) {
        Ok(body) => Response::bytes(status, body).content_type("application/json"),
        Err(_) => Response::conversion_failure(),
    }
}

/// Converts a business failure into an HTTP response generated by an API macro.
pub trait IntoHttpError {
    fn into_http_error(self, arena: &EphemeralBytesArena) -> Response;
}

/// Default structured HTTP API failure.
#[derive(Debug)]
pub struct ApiError {
    status: StatusCode,
    message: String,
}

impl std::fmt::Display for ApiError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&self.message)
    }
}

impl std::error::Error for ApiError {}

impl ApiError {
    #[must_use]
    pub fn new(status: StatusCode, message: impl Into<String>) -> Self {
        Self {
            status,
            message: message.into(),
        }
    }

    #[must_use]
    pub fn bad_request(message: impl Into<String>) -> Self {
        Self::new(StatusCode::BAD_REQUEST, message)
    }

    /// Returns a `403 Forbidden` API failure.
    ///
    /// Use this after authentication has established the caller's identity but
    /// authorization denies access to the requested resource or operation.
    #[must_use]
    pub fn forbidden(message: impl Into<String>) -> Self {
        Self::new(StatusCode::FORBIDDEN, message)
    }
}

/// Default result type for business methods exported through `#[api]`.
pub type ApiResult<T> = std::result::Result<T, ApiError>;

impl IntoHttpError for ApiError {
    fn into_http_error(self, arena: &EphemeralBytesArena) -> Response {
        json_response_with_status(
            self.status,
            ErrorPayload {
                error: self.message,
            },
            arena,
        )
    }
}

impl From<crate::HeaderBlockError> for ApiError {
    fn from(error: crate::HeaderBlockError) -> Self {
        Self::new(StatusCode::INTERNAL_SERVER_ERROR, error.to_string())
    }
}

impl IntoHttpError for crate::HeaderBlockError {
    fn into_http_error(self, arena: &EphemeralBytesArena) -> Response {
        ApiError::from(self).into_http_error(arena)
    }
}

impl From<crate::BodyError> for ApiError {
    fn from(error: crate::BodyError) -> Self {
        let status = if matches!(error, crate::BodyError::UnsupportedMediaType) {
            StatusCode::UNSUPPORTED_MEDIA_TYPE
        } else {
            StatusCode::BAD_REQUEST
        };
        Self::new(status, error.to_string())
    }
}

impl IntoHttpError for crate::BodyError {
    fn into_http_error(self, arena: &EphemeralBytesArena) -> Response {
        ApiError::from(self).into_http_error(arena)
    }
}

#[derive(Serialize)]
struct ErrorPayload {
    error: String,
}

fn encode_json<T>(
    value: T,
    arena: &EphemeralBytesArena,
) -> Result<crate::EphemeralBytes, serde_json::Error>
where
    T: Serialize,
{
    let mut measure = CountingWriter::default();
    serde_json::to_writer(&mut measure, &value)?;
    let mut output = arena.alloc(measure.len);
    serde_json::to_writer(ArenaWriter(&mut output), &value)?;
    Ok(output.freeze())
}

#[derive(Default)]
struct CountingWriter {
    len: usize,
}

impl Write for CountingWriter {
    fn write(&mut self, bytes: &[u8]) -> io::Result<usize> {
        self.len = self
            .len
            .checked_add(bytes.len())
            .ok_or_else(|| io::Error::other("JSON response is too large"))?;
        Ok(bytes.len())
    }

    fn flush(&mut self) -> io::Result<()> {
        Ok(())
    }
}

struct ArenaWriter<'a>(&'a mut EphemeralBytesMut);

impl Write for ArenaWriter<'_> {
    fn write(&mut self, bytes: &[u8]) -> io::Result<usize> {
        self.0.write(bytes)
    }

    fn flush(&mut self) -> io::Result<()> {
        Ok(())
    }
}
